# -*- coding: utf-8 -*-
"""Resampling_using_mne.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cxx_XUyZZPME0WtVM6Es_-viZ2z1tcUG
"""
#%%
# Installing packages
!pip install mne
!pip install pyedflib

#%%
# Importing required libraries
import mne
from mne.io import RawArray
#from mne.channels import Info
from pyedflib import highlevel

#%%
#Loading required file. Change path depending on file location.
file = '/content/FA7310SO_0001.edf'

#%%
# Reading the file
raw = mne.io.read_raw_edf(file, preload= True)

#%%
# Referencing the eeg data
raw_eeg = raw.resample(sfreq=250)

#%%
# Save the modified EEG data (export)
output_path = '/content/raw_eeg.fif'  # Replace with your desired path
raw.save(output_path, overwrite=True)

#%%
